const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const P={check:'<path d="M20 6 9 17l-5-5"/>',shield:'<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/>',clip:'<rect x="8" y="2" width="8" height="4" rx="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="m9 14 2 2 4-4"/>',file:'<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4M10 9H8M16 13H8M16 17H8"/>',truck:'<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2M15 18H9"/><path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14"/><circle cx="17" cy="18" r="2"/><circle cx="7" cy="18" r="2"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9 7 7M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1"/>'};
const I=(k,c='')=>`<svg class="ic ${c}" viewBox="0 0 24 24">${P[k]}</svg>`;
$$('.chk').forEach(u=>u.innerHTML=u.dataset.l.split('|').map(t=>`<li class="flex gap-2"><span class="text-emerald-400 shrink-0">${I('check')}</span>${t}</li>`).join(''));
// Reemplaza null por URLs de Unsplash (en esta vista publicada las imágenes remotas se bloquean y se muestra el respaldo).
const M=[['Inyectoras de Plástico','220V / 440V','35–45 días',null],['Líneas de Envasado','220V','40–50 días',null],['Cortadoras Láser CNC','220V / 440V','30–40 días',null],['Maquinaria Agrícola','440V','40–55 días',null]];
const ph=`<div class="absolute inset-0 grid place-items-center bg-[radial-gradient(circle_at_30%_20%,#1e3a6e,#0B132B)] text-slate-500"><svg class="w-16 h-16 fill-none stroke-current" viewBox="0 0 24 24" stroke-width="1.2">${P.gear}</svg></div>`;
$('#machines').innerHTML=M.map(m=>`<article class="box !p-0 overflow-hidden flex flex-col"><div class="relative aspect-[3/2] overflow-hidden">${ph}${m[3]?`<img src="${m[3]}" alt="${m[0]}" loading="lazy" class="relative w-full h-full object-cover" onerror="this.remove()">`:''}</div><div class="p-3 sm:p-4 flex flex-col gap-2 sm:gap-3 flex-1"><h3 class="h text-base sm:text-lg leading-tight">${m[0]}</h3><span class="text-xs font-semibold bg-amber-500/15 text-amber-300 rounded-full px-2 py-1 w-fit">⚡ ${m[1]} · México</span><p class="text-xs sm:text-sm">Tránsito: ${m[2]}</p><a href="#cotizar" class="btn ghost text-xs sm:text-sm !px-2 mt-auto text-center">Solicitar Ficha Técnica</a></div></article>`).join('');
$('#why').innerHTML=[['shield','Auditoría Legal de Proveedores en China','Verificamos existencia legal y licencias. Evita fraudes.'],['clip','Control de Calidad Pre-Embarque','Reporte fotográfico y video antes de pagar el saldo.'],['file','Gestión Aduanal Especializada','Cumplimiento de NOMs e impuestos SAT.'],['truck','Modalidad Puerta a Puerta DDP','Todo resuelto hasta tu bodega.']].map((w,i)=>`<div class="box flex gap-4"><div class="shrink-0 text-center"><span class="h text-3xl text-brand block">0${i+1}</span><span class="text-orange-300 mt-2 inline-block">${I(w[0])}</span></div><div><h3 class="font-bold text-white">${w[1]}</h3><p class="text-sm mt-1">${w[2]}</p></div></div>`).join('');
$('#steps').insertAdjacentHTML('beforeend',[['Solicitud y Viabilidad','Producto, fracción arancelaria y costos.'],['Negociación y Muestra','Precio negociado y muestra validada.'],['Producción e Inspección','Supervisión de fabricación y calidad.'],['Embarque y Despacho Aduanal','Flete, aduana y entrega.']].map((s,i)=>`<li class="relative pl-14 md:pl-0"><span class="absolute md:relative left-0 top-0 z-10 grid place-items-center w-10 h-10 rounded-full bg-brand text-white font-bold ring-4 ring-ink">${i+1}</span><h3 class="font-bold text-white mt-3">${s[0]}</h3><p class="text-sm mt-1">${s[1]}</p></li>`).join(''));
// logos (wordmarks en escala de grises; sustituir por los SVG oficiales)
const L={MAERSK:'<text x="60" y="26" text-anchor="middle" font-family="Arial" font-weight="700" font-size="17" letter-spacing="2">MAERSK</text><path d="M60 3l3 4h-6z"/>',COSCO:'<text x="60" y="27" text-anchor="middle" font-family="Georgia" font-weight="700" font-size="20" letter-spacing="3">COSCO</text>',EVERGREEN:'<text x="60" y="25" text-anchor="middle" font-family="Arial" font-weight="700" font-size="13" letter-spacing="1">EVERGREEN</text><rect x="18" y="29" width="84" height="2"/>','HAPAG-LLOYD':'<text x="60" y="26" text-anchor="middle" font-family="Arial" font-weight="700" font-size="12">Hapag-Lloyd</text>',MSC:'<text x="60" y="27" text-anchor="middle" font-family="Arial" font-weight="900" font-size="22" font-style="italic">MSC</text>',ONE:'<text x="60" y="27" text-anchor="middle" font-family="Arial" font-weight="900" font-size="22" letter-spacing="3">ONE</text>'};
$('#carriers').innerHTML=Object.entries(L).map(([n,s])=>`<div class="box !p-3 grid place-items-center grayscale opacity-60 hover:opacity-100 transition"><svg viewBox="0 0 120 34" class="w-full h-9 fill-slate-300" role="img" aria-label="${n}">${s}</svg></div>`).join('');
const F=[['¿Necesito padrón de importadores propio?','Si importas a tu nombre, sí. Si aún no lo tienes, te asesoramos para tramitarlo u operar bajo nuestro esquema.'],['¿Cómo garantizan que la maquinaria funcione en México?','Validamos voltaje (220V/440V), 60Hz, cumplimiento de NOMs y probamos el equipo en fábrica antes del embarque.'],['¿Cuánto tarda un contenedor marítimo de China a México?','Entre 30 y 45 días de tránsito puerto a puerto, más despacho aduanal y entrega.'],['¿Emiten factura fiscal mexicana (CFDI)?','Sí, emitimos CFDI por todos nuestros servicios.']];
$('#faq').innerHTML=F.map((f,i)=>`<div class="box !p-0"><button class="w-full flex justify-between gap-3 p-4 text-left font-semibold text-white">${f[0]}<span>▾</span></button><p class="px-4 pb-4 ${i?'hide':''}">${f[1]}</p></div>`).join('');
$$('#faq button').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('hide'));
let step=0;const v={};
$$('[data-k]').forEach(g=>g.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{g.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));c.classList.add('on');v[g.dataset.k]=c.textContent}));
function show(){$$('[data-s]').forEach(e=>e.classList.toggle('hide',+e.dataset.s!==step));$('#stepLbl').textContent=`Paso ${step+1} de 3`;$('#back').classList.toggle('hide',!step);$('#next').classList.toggle('hide',step===2);$('#send').classList.toggle('hide',step!==2);$('#err').textContent=''}
$('#next').onclick=()=>{if(step===0&&!v.op)return $('#err').textContent='Selecciona una opción';if(step===1&&(!v.carga||!v.inc))return $('#err').textContent='Selecciona carga e incoterm';step++;show()};
$('#back').onclick=()=>{step--;show()};
$('#rfq').onsubmit=e=>{e.preventDefault();const g=n=>document.getElementsByName(n)[0].value.trim();
 const x=g('nombre').length<2?'Nombre requerido':g('empresa').length<2?'Empresa requerida':!/^\S+@\S+\.\S+$/.test(g('correo'))?'Correo inválido':g('tel').replace(/\D/g,'').length<10?'Teléfono: mínimo 10 dígitos':'';
 if(x)return $('#err').textContent=x;$('#rfq').classList.add('hide');$('#ok').classList.remove('hide')};
show();
// modales
const open=id=>$(id).classList.remove('hide');
$$('#credit,#wcModal').forEach(m=>{m.onclick=e=>{if(e.target===m||e.target.classList.contains('x'))m.classList.add('hide')}});
const mb=$('#mb'),mn=$('#mnav');mb.onclick=()=>{const o=mn.classList.toggle('hide');mb.setAttribute('aria-expanded',String(!o))};mn.onclick=e=>{if(e.target.tagName=='A'){mn.classList.add('hide');mb.setAttribute('aria-expanded','false')}};
$('#creditBtn').onclick=()=>open('#credit');$('#wcBtn').onclick=()=>open('#wcModal');
addEventListener('keydown',e=>{if(e.key==='Escape')$$('#credit,#wcModal').forEach(m=>m.classList.add('hide'))});
// QR mockup 25x25 con 3 esquinas fijas
let q='';const f=(x,y)=>{q+=`<rect x="${x}" y="${y}" width="7" height="7" fill="#0B132B"/><rect x="${x+1}" y="${y+1}" width="5" height="5" fill="#fff"/><rect x="${x+2}" y="${y+2}" width="3" height="3" fill="#0B132B"/>`};f(0,0);f(18,0);f(0,18);
for(let i=0;i<625;i++){const x=i%25,y=i/25|0;if((x<8&&y<8)||(x>16&&y<8)||(x<8&&y>16))continue;if((x*7+y*13+x*y)%3===0)q+=`<rect x="${x}" y="${y}" width="1" height="1" fill="#0B132B"/>`}
$('#qr').innerHTML=q;
